name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: bazoocaze/github-actions/maven-setup@v1
        with:
          java-version: "21"
          github-owner: "bazoocaze"

      - name: Build with Maven
        run: mvn -B compile --file pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}